
version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - static_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - static_volume:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
